### ISSUE TITLE
Open the map centered in a specific feature

### ISSUE THREAD

**Issue by oscarfonts** [geodata/GeoExplorer#20]
Let map request specify a certain feature and open the map view centered on that feature.

The feature will be specified by its ID. In a general case, we could request any feature on any layer based on any field with unique values.

PROPOSAL

Interface:

Add the parameter "zoomToFeature" to the GET request. It will contain three values: layer ID, field name, and field value, separated by semicolons.

Example: zoomToFeature=poum:parcela;REFCAT;4691111

Behaviour:

This will be implemented as a GXP control that will search for the layer ID in the actual layer tree, after the viewer is initialized, and proceed as follows:
- If layer is not found in the layer tree, notify user and abort.
- Force layer visibility.
- Send WFS request with CQL filter specifying feature field and value (eg. CQL=REFCAT%3D4691111). Refer to searchers implementation.
- If WFS response is erroneous or empty (no features), notify user and abort.
- Get first feature from WFS response, and zoom to feature extent.

**Comment by mpericay** [comment]
first hardcoded version (branch urlapi) works with
localhost:6969/gdviewer?ref=3612003DF1931S#maps/2

TODO: move to module (not in Geoexplorer.js), get other parameters via URL (field, layer), error management, maybe highlight?
